---
openapi: 3.0.3
info:
  version: 1.0.0
  title: REST API
paths:
  /item/add:
    post:
      operationId: add
      description: add
      parameters:
        - name: "name"
          schema:
            type: "string"
          in: query
        - name: "amount"
          schema:
            type: "number"
          in: query
      responses:
        "204":
          description: item added succesfully
        "400":
          description: request errors
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AddErrors"
  /item/remove:
    post:
      operationId: remove
      description: remove
      parameters:
        - name: "name"
          schema:
            type: "string"
          in: query
      responses:
        "204":
          description: item removed succesfully
        "400":
          description: request errors
          content:
              application/json:
                schema:
                  $ref: "#/components/schemas/RemoveErrors"
  /item/list:
      get:
        operationId: list
        description: list
        responses:
          "200":
            description: the item list
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Items"
components:
  schemas:
    Items:
      type: array
      items:
          $ref: "#/components/schemas/Item"
    Item:
      type: object
      properties:
        name:
          type: string
          description: the item name
        amount:
          type: number
          description: the item amount
      required:
        - name
        - amount
    AddErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/AddError"
      required:
        - errors
    AddError:
      type: string
      enum:
        - MISSING_NAME
        - EXISTING_NAME
        - MISSING_AMOUNT
        - AMOUNT_MINIMUM
    RemoveErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/RemoveError"
      required:
        - errors
    RemoveError:
      type: string
      enum:
        - MISSING_NAME
        - UNKNOWN_NAME