@startsalt

' Enterprise JSF project.
'
' Copyright 2021-2023 e-Contract.be BV. All rights reserved.
' e-Contract.be BV proprietary/confidential. Use is subject to license terms.

{
    {T
        + Maven EAR project
            ++ pom.xml
            ++ taglib
                +++ pom.xml
                +++ src/main
                    ++++ resources/META-INF
                        +++++ ejsf.taglib.xml
                        +++++ beans.xml
                        +++++ faces-config.xml
                        +++++ resources
                            ++++++ ...
                    ++++ java
                        +++++ ...
            ++ war
                +++ pom.xml
                +++ src/main
                    ++++ webapp
                        +++++ index.xhtml
                        +++++ ...
                        +++++ WEB-INF
                            ++++++ web.xml
                            ++++++ faces-config.xml
                            ++++++ beans.xml
                    ++++ java
                        +++++ ...
            ++ ear
                +++ pom.xml
    }
}

@endsalt
