@startfiles

' Enterprise JSF project.
'
' Copyright 2021-2024 e-Contract.be BV. All rights reserved.
' e-Contract.be BV proprietary/confidential. Use is subject to license terms.

/pom.xml
/taglib/pom.xml
/taglib/src/main/resources/META-INF/ejsf.taglib.xml
/taglib/src/main/resources/META-INF/beans.xml
/taglib/src/main/resources/META-INF/faces-config.xml
/taglib/src/main/resources/META-INF/web-fragment.xml
/taglib/src/main/resources/META-INF/resources/...
/taglib/src/main/java/...
/war/pom.xml
/war/src/main/webapp/index.xhtml
/war/src/main/webapp/...
/war/src/main/webapp/WEB-INF/web.xml
/war/src/main/webapp/WEB-INF/faces-config.xml
/war/src/main/webapp/WEB-INF/beans.xml
/war/src/main/java/...
/ear/pom.xml

@endfiles
