@startuml

' Enterprise JSF project.
'
' Copyright 2021-2023 e-Contract.be BV. All rights reserved.
' e-Contract.be BV proprietary/confidential. Use is subject to license terms.

component EAR {
    component taglib
    component WAR
}

WAR -> taglib

@enduml
