@startfiles

' Enterprise JSF project.
'
' Copyright 2024 e-Contract.be BV. All rights reserved.
' e-Contract.be BV proprietary/confidential. Use is subject to license terms.

/pom.xml
/src/main/webapp/index.xhtml
/src/main/webapp/...
/src/main/webapp/WEB-INF/web.xml
/src/main/webapp/WEB-INF/jboss-web.xml
/src/main/webapp/WEB-INF/faces-config.xml
/src/main/webapp/WEB-INF/beans.xml
/src/main/webapp/WEB-INF/...
/src/main/java/...

@endfiles
